import Foundation

/// A per-app translation table: maps canonical shortcut IDs to native actions.
///
/// Each adapter targets a single application (by bundle ID) or web app
/// (by domain). When the user presses a canonical shortcut while that app
/// is frontmost, the engine looks up the mapping and executes the native action.
public struct Adapter: Codable, Equatable, Identifiable {
    /// The app's bundle identifier (e.g., "com.microsoft.VSCode")
    /// or a web-app prefixed domain (e.g., "web:notion.so").
    public let appIdentifier: String

    /// Human-readable app name for the UI.
    public let appName: String

    /// Where this adapter came from.
    public let source: Source

    /// The individual shortcut mappings.
    public var mappings: [Mapping]

    public var id: String { appIdentifier }

    public init(
        appIdentifier: String,
        appName: String,
        source: Source = .builtin,
        mappings: [Mapping]
    ) {
        self.appIdentifier = appIdentifier
        self.appName = appName
        self.source = source
        self.mappings = mappings
    }
}

// MARK: - Source

extension Adapter {
    /// How this adapter was created — used for trust and priority ordering.
    public enum Source: String, Codable, Hashable {
        /// Shipped with the app, hand-verified.
        case builtin
        /// Auto-generated by menu introspection (Phase 2).
        case menuIntrospection
        /// Generated by LLM adapter generator (Phase 4, future).
        case llmGenerated
        /// Downloaded from community repository (Phase 5, future).
        case community
        /// Created or edited by the user.
        case user
    }
}

// MARK: - Mapping

extension Adapter {
    /// A single canonical → native translation within an adapter.
    public struct Mapping: Codable, Equatable, Identifiable {
        /// The canonical shortcut ID this mapping handles (e.g., "focus_url_bar").
        public let canonicalID: String

        /// How to execute the native action.
        public let method: Method

        /// For `.keyRemap`: the native key combo to send instead.
        public let nativeKeys: KeyCombo?

        /// For `.menuInvoke`: the menu item title to trigger via AX.
        public let menuTitle: String?

        /// For `.axAction`: the AX action string (e.g., "AXPress").
        public let axAction: String?

        /// Optional context filter — only apply when this UI context is active.
        /// e.g., "editor", "terminal", "sidebar" (Phase 2+).
        public let context: String?

        public var id: String { canonicalID }

        public init(
            canonicalID: String,
            method: Method,
            nativeKeys: KeyCombo? = nil,
            menuTitle: String? = nil,
            axAction: String? = nil,
            context: String? = nil
        ) {
            self.canonicalID = canonicalID
            self.method = method
            self.nativeKeys = nativeKeys
            self.menuTitle = menuTitle
            self.axAction = axAction
            self.context = context
        }
    }
}

// MARK: - Method

extension Adapter.Mapping {
    /// The mechanism used to translate a canonical shortcut into a native action.
    public enum Method: String, Codable {
        /// Rewrite the CGEvent to a different keycode+modifiers.
        case keyRemap

        /// Invoke a menu item via AXUIElement (Phase 2).
        case menuInvoke

        /// Perform an arbitrary AX action (Phase 2).
        case axAction

        /// The canonical shortcut is the same as the native one — pass through.
        case passthrough
    }
}
